### ISSUE TITLE
obfuscate_email: Jekyll is revertingthe HTML entities generated by the filter

### ISSUE THREAD

**Issue by eksperimental** [alexwlchan/alexwlchan.net#470] opened 2022-02-01 19:25 UTC
`{{ 'hi@example.com' | create_mailto_link }}`

will generate

`<a href="m&#97;ilt&#111;&#x3a;&#x68;&#105;&#x40;&#101;&#x78;&#x61;&#x6d;&#x70;&#108;&#101;&#46;&#x63;&#111;&#x6d;">hi@example.com</a>`

**Comment by eksperimental** [comment] 2022-02-01 19:27
I just found a solution:

add to _config.yml

```md
kramdown:
  entity_output: :as_input
```

**Comment by alexwlchan** [comment] 2022-02-01 21:52
Yes, that's the intended behaviour of this plugin. I'm not sure what problem you're reporting?

**Comment by eksperimental** [comment] 2022-02-01 22:56
Well.. the intention of the plugin is to obfuscate the email address, and it is in plain text.
So spammers can still scrap the address.

also `{{ 'hi@example.com' | encode_email }}` does nothing because the what the plugin does it is reverted by the markdown parser

**Comment by alexwlchan** [comment] 2022-02-01 22:58
Ah yeah, I see now. Thanks for letting me know.

**Comment by eksperimental** [comment] 2022-02-01 23:00
> Ah yeah, I see now. Thanks for letting me know.

Maybe there is nothing that can be done here, maybe there is a work around, but I think it should be documented.

**Comment by alexwlchan** [comment] 2024-05-29 20:17
I'm no longer using this filter and I've deleted all the relevant code, so I'm going to close this issue.

**Closed by alexwlchan** 2024-05-29 20:17 UTC
